import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy — Randomize.one',
  description: 'Privacy policy for Randomize.one. Learn how we protect your data. All tools run entirely in your browser with zero data collection.',
  alternates: { canonical: 'https://randomize.one/privacy' },
  openGraph: {
    title: 'Privacy Policy — Randomize.one',
    description: 'Privacy policy for Randomize.one. All tools run entirely in your browser with zero data collection.',
    url: 'https://randomize.one/privacy',
  },
};

export default function PrivacyPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <h1 className="text-3xl sm:text-4xl font-bold text-text mb-2">Privacy Policy</h1>
      <p className="text-text-muted mb-8">Last updated: April 2026</p>

      <div className="space-y-8">
        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Overview</h2>
          <p className="text-text-light leading-relaxed">
            Randomize.one is committed to protecting your privacy. This privacy policy explains how we handle information when you use our website. The short version: we collect virtually nothing. All of our randomize tools run entirely in your browser, and no data you generate is ever sent to our servers.
          </p>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Client-Side Processing</h2>
          <p className="text-text-light leading-relaxed">
            All random generation tools on Randomize.one operate entirely within your web browser using client-side JavaScript. This means that all numbers, strings, colors, coin flips, dice rolls, and name selections are generated locally on your device. No input data, generated results, or tool configurations are transmitted to any server. When you close your browser tab, all data is permanently erased from memory.
          </p>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Information We Do Not Collect</h2>
          <ul className="space-y-2 text-text-light">
            <li className="flex items-start gap-2">
              <span className="text-success font-bold mt-0.5">&#10003;</span>
              <span>We do not collect any personal information (name, email, address, phone number).</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-success font-bold mt-0.5">&#10003;</span>
              <span>We do not collect or store any data you enter into our tools (numbers, names, strings).</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-success font-bold mt-0.5">&#10003;</span>
              <span>We do not collect or store any results generated by our tools.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-success font-bold mt-0.5">&#10003;</span>
              <span>We do not use browser fingerprinting or device identification techniques.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-success font-bold mt-0.5">&#10003;</span>
              <span>We do not create user profiles or track individual behavior across sessions.</span>
            </li>
          </ul>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Local Storage</h2>
          <p className="text-text-light leading-relaxed">
            Our website uses browser local storage solely to remember your theme preference (light or dark mode). This data is stored only on your device and is never transmitted to any server. You can clear this data at any time through your browser settings. No other data is stored in local storage, session storage, or IndexedDB.
          </p>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Cookies</h2>
          <p className="text-text-light leading-relaxed">
            Randomize.one does not set any first-party cookies. We do not use cookies for tracking, analytics, or advertising purposes. If third-party advertising is displayed on our site, those ad networks may set their own cookies according to their respective privacy policies. You can control cookie behavior through your browser settings.
          </p>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Third-Party Services</h2>
          <p className="text-text-light leading-relaxed">
            Our website may display advertisements from third-party ad networks. These services may collect anonymous usage data such as page views and general geographic location for the purpose of serving relevant advertisements. We do not control the data practices of these third-party services. We encourage you to review their respective privacy policies for more information about their data handling practices.
          </p>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Data Security</h2>
          <p className="text-text-light leading-relaxed">
            Since we do not collect or store user data, there is no user data to secure on our servers. All random generation uses the Web Crypto API, which provides cryptographically secure randomness. Our website is served over HTTPS to ensure that all communication between your browser and our servers is encrypted in transit.
          </p>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Children&#39;s Privacy</h2>
          <p className="text-text-light leading-relaxed">
            Our tools are suitable for users of all ages. Since we do not collect any personal information, there are no special concerns regarding children&#39;s privacy. Our tools can be safely used by students and minors without any data collection risks.
          </p>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Changes to This Policy</h2>
          <p className="text-text-light leading-relaxed">
            We may update this privacy policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. Any changes will be posted on this page with an updated revision date. We encourage you to review this policy periodically.
          </p>
        </section>

        <section className="bg-surface border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-semibold text-text mb-3">Contact Us</h2>
          <p className="text-text-light leading-relaxed">
            If you have any questions about this privacy policy or our data practices, please contact us at <span className="text-primary">hello@randomize.one</span>. You can also visit our <Link href="/about" className="text-primary hover:underline">About page</Link> to learn more about Randomize.one.
          </p>
        </section>
      </div>
    </div>
  );
}
